name: Krzysiek Przygudzki's blog
description: Blogging about java and stuffs
meta_description: "Krzysiek Przygudzki blogging about java and stuffs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: kprzygudzki.github.io
domain_name: 'http://kprzygudzki.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'kprzygudzki.github.io'
author:         'Krzysiek Przygudzki'
